---
- name: Host Info Facts
  command: "{{command}}"
  register: host_info
  
- name: Print Host Name
  debug:
    msg: "hostName is {{host_info.stdout}}"

- name: Install Nginx
  command: amazon-linux-extras install nginx1 -y
    
- name: Start Nginx
  service:
    name: nginx
    state: started
